"""Fix role and role_permission model relationships

Revision ID: 1adf4c1f000f
Revises: 5b9f64d23075
Create Date: 2025-03-30 16:04:06.912972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1adf4c1f000f'
down_revision: Union[str, None] = '5b9f64d23075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('roluuid', sa.UUID(), nullable=False),
    sa.Column('permissionuuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permissionuuid'], ['permissions.permissionuuid'], ),
    sa.ForeignKeyConstraint(['roluuid'], ['roles.roluuid'], ),
    sa.PrimaryKeyConstraint('roluuid', 'permissionuuid')
    )
    op.drop_table('role_permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission',
    sa.Column('roluuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permissionuuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permissionuuid'], ['permissions.permissionuuid'], name='role_permission_permissionuuid_fkey'),
    sa.ForeignKeyConstraint(['roluuid'], ['roles.roluuid'], name='role_permission_roluuid_fkey'),
    sa.PrimaryKeyConstraint('roluuid', 'permissionuuid', name='role_permission_pkey')
    )
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
