"""Inicial

Revision ID: e565c1ffcc63
Revises: 
Create Date: 2025-04-02 11:01:38.876264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e565c1ffcc63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permissionuuid', sa.UUID(), nullable=False),
    sa.Column('permissionname', sa.String(length=50), nullable=False),
    sa.Column('permissiondesc', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('permissionuuid')
    )
    op.create_index(op.f('ix_permissions_permissionname'), 'permissions', ['permissionname'], unique=True)
    op.create_table('roles',
    sa.Column('roluuid', sa.UUID(), nullable=False),
    sa.Column('rolname', sa.String(length=50), nullable=False),
    sa.Column('roldesc', sa.String(length=80), nullable=True),
    sa.Column('rolstatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('roluuid')
    )
    op.create_index(op.f('ix_roles_rolname'), 'roles', ['rolname'], unique=True)
    op.create_table('users',
    sa.Column('useruuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('userpass', sa.String(), nullable=False),
    sa.Column('useremail', sa.String(length=80), nullable=False),
    sa.Column('userfirstname', sa.String(length=50), nullable=False),
    sa.Column('userlastname', sa.String(length=50), nullable=False),
    sa.Column('userphone', sa.String(length=10), nullable=True),
    sa.Column('userstatus', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('useruuid')
    )
    op.create_index(op.f('ix_users_useremail'), 'users', ['useremail'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('roluuid', sa.UUID(), nullable=False),
    sa.Column('permissionuuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permissionuuid'], ['permissions.permissionuuid'], ),
    sa.ForeignKeyConstraint(['roluuid'], ['roles.roluuid'], ),
    sa.PrimaryKeyConstraint('roluuid', 'permissionuuid')
    )
    op.create_table('user_roles',
    sa.Column('useruuid', sa.UUID(), nullable=False),
    sa.Column('roluuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['roluuid'], ['roles.roluuid'], ),
    sa.ForeignKeyConstraint(['useruuid'], ['users.useruuid'], ),
    sa.PrimaryKeyConstraint('useruuid', 'roluuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_useremail'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_rolname'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_permissionname'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
